### ISSUE TITLE
Exception thrown when trying to transpile with latest Visual Studio Update

### ISSUE THREAD

**Issue by dotnetshadow** [madskristensen/TypeScriptCompileOnSave#2]
An exception is thrown when trying to transpile, this was working before the latest update (May 11th 2017)

### Installed product versions
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.4) Release
VisualStudio.15.Release/15.2.0+26430.4

### Description
Replace this text with a short description

### Steps to recreate
1. Create a javascript file
2. transpile to javascript 
3. file isn't being created

### Current behavior
11/05/2017 2:59:48 PM: System.Runtime.InteropServices.COMException (0x80004005): Command "SolutionExplorer.SyncWithActiveDocument" is not available.
   at EnvDTE._DTE.ExecuteCommand(String CommandName, String CommandArgs)
   at TypeScriptCompileOnSave.VsHelpers.OpenFileAndSelect(DTE dte, String file) in C:\projects\typescriptcompileonsave\src\Shared\VsHelpers.cs:line 80
   at TypeScriptCompileOnSave.AddConfigFile.<Execute>d__11.MoveNext() in C:\projects\typescriptcompileonsave\src\Commands\AddConfigFile.cs:line 88.

**Comment by dotnetshadow** [comment]
@madskristensen Just to add to this error:

I tested this in Visual Studio 2017 15.3 Preview (.NET core 2.0) and the transpilation seems to work.

Although when first creating the ts.config file from the context menu the exception is still thrown.

So to recap:
Visual Studio 15.2 (26403.7) **WORKING**
Visual Studio 15.2 (26430.6) **NOT WORKING**
Visual Studio 15.3 (Preview) **WORKING**

**Comment by dotnetshadow** [comment]
@madskristensen I was wondering if there has been any update on this issue?

**Comment by madskristensen** [comment]
Are you using the "Open Folder" feature or do you have a solution with a project?

**Comment by dotnetshadow** [comment]
@madskristensen I actually get the issue if I create a new asp.net core 1.1 project in visual studio 2017

What is the open folder feature?

**Comment by madskristensen** [comment]
@dotnetshadow did you try the latest [CI build](http://vsixgallery.com/extension/d6330ef4-ab82-4ab1-9828-4e43639e7521/) where it may have been fixed?

**Comment by dotnetshadow** [comment]
@madskristensen Yep I did try the CI build. While the exception I think maybe fixed, the transpilation doesn't work 

I've attached a simple project. On my machine I don't see any transpiling occuring
[WebApplication7.zip](https://github.com/madskristensen/TypeScriptCompileOnSave/files/1049092/WebApplication7.zip)

**Visual Studio details:**
Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
Version 4.7.02046

**Comment by dotnetshadow** [comment]
@madskristensen Thank you just confirming that the CI build does indeed work correctly 👍

**Comment by madskristensen** [comment]
@dotnetshadow thanks for verifying. I just released the update to the marketplace
